/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details take a look at the Writing Custom Plugins chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.2/userguide/custom_plugins.html
 */

plugins {
    id("com.gradle.plugin-publish") version "0.16.0"
    `java-gradle-plugin`
    `maven-publish`

    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.5.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    google()
}

group = "dk.acto"
version = System.getProperty("versionOverride")?.trim() ?: "1.0"

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    implementation("com.google.api-client:google-api-client:1.30.4")
    implementation("com.google.auth:google-auth-library-oauth2-http:1.2.0")
    implementation("com.google.apis:google-api-services-sheets:v4-rev581-1.25.0")
}

gradlePlugin {
    plugins {
        create("i18nPlugin") {
            id = "dk.acto.gradle.i18nplugin"
            implementationClass = "dk.acto.gradle.i18nplugin.I18nPlugin"
        }
    }
}

pluginBundle {
    website = "https://github.com/actoaps/gradle-i18n-plugin"
    vcsUrl = "https://github.com/actoaps/gradle-i18n-plugin"

    description = "Generates a JSON file with internationalized texts, based on a Google Sheet."

    (plugins) {
        "i18nPlugin" {
            displayName = "Gradle I18n Plugin"
            tags = listOf("gsheet", "i18n")
        }
    }
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    kotlinOptions {
        jvmTarget = "15"
    }
}

publishing {
    repositories {
        mavenLocal()
    }
}
