name: Release to Gradle Plugin Central

on:
  push:
    branches:
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Calculate version
        id: spell
        uses: actoaps/version-spell@v3

      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Gradle Build
        run: ./gradlew clean build -DversionOverride=$BUILD_ID
        env:
          BUILD_ID: ${{ steps.spell.outputs.version }}

      - name: Setup Gradle Plugin Central auth
        run: |
          mkdir -p ~/.gradle
          echo $GRADLE_PUBLISH_KEY_AND_SECRET >> ~/.gradle/gradle.properties
        env:
          GRADLE_PUBLISH_KEY_AND_SECRET: ${{ secrets.GRADLE_PUBLISH_KEY_AND_SECRET }}

      - name: Release client to Gradle Plugin Central
        run: ./gradlew publishPlugins
